### ISSUE TITLE
about "Replace scripts in LLaVA/scripts."

### ISSUE THREAD

**Issue by gyuilLim** [Linziyang1999/VGA-visual-GUI-assistant#3]
Hello,

Thank you for providing this amazing project! I have a question about the instruction: "Replace scripts in LLaVA/scripts."

Could you clarify which specific scripts we need to replace and with what files? I want to ensure I'm following the steps correctly.

Thank you for your help!

**Comment by Linziyang1999** [comment]
training code here. https://github.com/Linziyang1999/llava

**Comment by gyuilLim** [comment]
thank you!!
